"""
arduino_mcp_toolkit.generator — Code generation engine
"""
from __future__ import annotations
import os
import logging
from typing import Any
from arduino_mcp_toolkit.utils import get_config

logger = logging.getLogger("arduino-mcp")


class SketchGenerator:
    """Generate production-ready Arduino sketches from natural language."""

    def generate(self, description: str, features: list[str] = None, include_tests: bool = True) -> str:
        features = features or []
        lines = [
            "/**",
            f" * Auto-generated sketch for: {description}",
            f" * Features: {', '.join(features) or 'none'}",
            " * Generated by arduino-mcp-toolkit",
            " */",
            "",
            '#include <Arduino.h>',
        ]

        # Add feature-specific includes
        if "wifi" in features:
            lines.append('#include <WiFiNINA.h>')
        if "ble" in features:
            lines.append('#include <ArduinoBLE.h>')
        if "imu" in features:
            lines.append('#include <Adafruit_LSM6DSOX.h>')
        if "mic" in features:
            lines.append('#include <PDM.h>')
        if "oled" in features:
            lines.append('#include <Wire.h>')
            lines.append('#include <Adafruit_GFX.h>')
            lines.append('#include <Adafruit_SSD1306.h>')
        if "tinyml" in features:
            lines.append('#include <TensorFlowLite.h>')
        if "crypto" in features:
            lines.append('#include <ArduinoECCX08.h>')
        if "power_mgmt" in features:
            lines.append('#include <ArduinoLowPower.h>')

        lines.append("")

        # Add HAL interfaces
        if any(f in features for f in ["wifi", "ble", "imu", "mic", "tinyml", "crypto"]):
            lines.extend([
                "// ── HAL Interface Contracts (frozen) ──────────────────────────",
                "class ISensor {",
                "public:",
                "  virtual ~ISensor() = default;",
                "  virtual int init() = 0;",
                "  virtual int read(void* data, int len) = 0;",
                "};",
                "",
                "class IRadio {",
                "public:",
                "  virtual ~IRadio() = default;",
                "  virtual int init() = 0;",
                "  virtual int connect(const char* ssid, const char* pass) = 0;",
                "  virtual int advertise(const char* name) = 0;",
                "};",
                "",
                "class IModelRuntime {",
                "public:",
                "  virtual ~IModelRuntime() = default;",
                "  virtual int load(const uint8_t* model, int len) = 0;",
                "  virtual int invoke(const int8_t* input, int8_t* output) = 0;",
                "};",
                "",
            ])

        # Add globals
        lines.extend([
            "// ── Configuration ──────────────────────────────────────────────",
            "constexpr uint32_t SERIAL_BAUD = 115200;",
            "constexpr uint32_t SENSOR_RATE_HZ = 10;",
            "constexpr uint32_t INFERENCE_RATE_HZ = 20;",
            "",
        ])

        # Add setup/loop
        lines.extend([
            "// ── Entry Points ──────────────────────────────────────────────",
            "void setup() {",
            "  Serial.begin(SERIAL_BAUD);",
            "  while (!Serial) { delay(10); }",
            "  Serial.println(\"[SKETCH] Starting...\");",
            "",
        ])

        # Feature-specific setup
        if "wifi" in features:
            lines.extend([
                "  // Wi-Fi setup",
                "  if (WiFi.status() == WL_NO_MODULE) {",
                "    Serial.println(\"[ERROR] NINA-W102 not found\");",
                "    while (true) delay(1000);",
                "  }",
                "  WiFi.begin();",
                "",
            ])
        if "ble" in features:
            lines.extend([
                "  // BLE setup",
                "  if (!BLE.begin()) {",
                "    Serial.println(\"[ERROR] BLE init failed\");",
                "    while (true) delay(1000);",
                "  }",
                "  BLE.setLocalName(\"ARP-2040\");",
                "  BLE.advertise();",
                "",
            ])
        if "imu" in features:
            lines.extend([
                "  // IMU setup",
                "  // IMU.begin(); // TODO: Initialize LSM6DSOX",
                "",
            ])
        if "power_mgmt" in features:
            lines.extend([
                "  // Power management",
                "  LowPower.begin();",
                "",
            ])

        lines.extend([
            "  Serial.println(\"[SKETCH] Ready\");",
            "}",
            "",
            "void loop() {",
            "  // Main loop — use FreeRTOS tasks for real work",
            "  delay(100);",
            "}",
            "",
        ])

        # Add tests if requested
        if include_tests:
            lines.extend([
                "// ── Unit Tests ───────────────────────────────────────────────",
                "#ifdef UNIT_TEST",
                "#include <unity.h>",
                "",
                "void test_setup() {",
                "  TEST_ASSERT_EQUAL(0, 0);",
                "}",
                "",
                "void test_loop() {",
                "  // Add tests here",
                "}",
                "",
                "int main() {",
                "  UNITY_BEGIN();",
                "  RUN_TEST(test_setup);",
                "  RUN_TEST(test_loop);",
                "  return UNITY_END();",
                "}",
                "#endif",
            ])

        return "\n".join(lines)


class HALGenerator:
    """Generate complete HAL interface + implementation scaffolding."""

    def generate(self, board: str, output_dir: str) -> list[str]:
        os.makedirs(output_dir, exist_ok=True)
        files = []

        interfaces = ["ISensor", "IRadio", "ICrypto", "IStorage", "IPower", "IAudio", "IDisplay", "IActuator"]

        for iface in interfaces:
            # Header
            header_path = os.path.join(output_dir, f"{iface}.h")
            header = [
                f"#ifndef {iface.upper()}_H",
                f"#define {iface.upper()}_H",
                "",
                f"class {iface} {{",
                "public:",
                f"  virtual ~{iface}() = default;",
                f"  virtual int init() = 0;",
                "",
                "  // Implementations must override",
                "",
                "protected:",
                "  int _initialized = 0;",
                "};",
                "",
                f"#endif // {iface.upper()}_H",
            ]
            with open(header_path, "w") as f:
                f.write("\n".join(header))
            files.append(f"{iface}.h")

            # Implementation stub
            impl_path = os.path.join(output_dir, f"{iface}.cpp")
            impl = [
                f"#include \"{iface}.h\"",
                "",
                f"// {iface} implementation for {board}",
                f"// TODO: Implement with board-specific drivers",
                "",
            ]
            with open(impl_path, "w") as f:
                f.write("\n".join(impl))
            files.append(f"{iface}.cpp")

        return files


class ProjectGenerator:
    """Generate complete PlatformIO project structure."""

    def generate(self, name: str, board: str, output_dir: str, framework: str = "platformio", features: list[str] = None) -> list[str]:
        features = features or []
        os.makedirs(output_dir, exist_ok=True)
        os.makedirs(os.path.join(output_dir, "src"), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "include"), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "lib"), exist_ok=True)
        os.makedirs(os.path.join(output_dir, "test"), exist_ok=True)
        files = []

        # platformio.ini
        ini_path = os.path.join(output_dir, "platformio.ini")
        ini = [
            "[env:native]",
            "platform = native",
            "test_build_src = yes",
            "",
            f"[env:{board.replace(':', '_')}]",
            f"platform = {self._platform_for_board(board)}",
            f"board = {board.split(':')[-1]}",
            "framework = arduino",
            "monitor_speed = 115200",
            "build_flags =",
            "  -Wall",
            "  -Wextra",
        ]
        if "tinyml" in features:
            ini.append("  -DTF_LITE_STATIC_MEMORY")
            ini.append("  -DTF_LITE_MCU_PRESENT")
        ini.extend([
            "",
            "lib_deps =",
            "  # Add your dependencies here",
            "",
        ])
        with open(ini_path, "w") as f:
            f.write("\n".join(ini))
        files.append("platformio.ini")

        # src/main.cpp
        main_path = os.path.join(output_dir, "src", "main.cpp")
        with open(main_path, "w") as f:
            f.write("#include <Arduino.h>\n\nvoid setup() { Serial.begin(115200); }\nvoid loop() {}\n")
        files.append("src/main.cpp")

        # CMakeLists.txt
        cmake_path = os.path.join(output_dir, "CMakeLists.txt")
        cmake = [
            f"cmake_minimum_required(VERSION 3.20)",
            f"project({name})",
            "",
            "set(CMAKE_CXX_STANDARD 17)",
            "",
        ]
        with open(cmake_path, "w") as f:
            f.write("\n".join(cmake))
        files.append("CMakeLists.txt")

        return files

    def _platform_for_board(self, board: str) -> str:
        if "rp2040" in board.lower():
            return "https://github.com/platformio/platform-raspberrypi.git"
        elif "esp32" in board.lower():
            return "espressif32"
        elif "avr" in board.lower() or "uno" in board.lower() or "nano" in board.lower():
            return "atmelavr"
        elif "stm32" in board.lower():
            return "ststm32"
        return "atmelavr"
